version: '3.8'

services:
  flaskapp:
    volumes:
      - ./Scores.txt:/app/Scores.txt
      
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:8777"
    environment:
      - FLASK_APP=main_score.py
    restart: unless-stopped


